version: '3'

services:

    # app:
    #     build:
    #         context: .
    #         dockerfile: Dockerfile
    #     image: registry.medhub.uz/medhub-core-uz:latest
    #     command: "uvicorn main:app --reload"
    #     networks:
    #         - app-net
    #     depends_on:
    #         - postgresdb
    #     ports:
    #         - '8000:8000'
    #     environment:
    #         - POSTGRES_DATABASE
    #         - POSTGRES_USERNAME
    #         - POSTGRES_PASSWORD
    #         - POSTGRES_HOST

    postgresdb:
        container_name: postgres
        image: postgres
        networks:
            - app-net
        volumes:
            - sample_db:/var/lib/postgresql/data
        ports:
            - '5435:5432'
        environment:
            - POSTGRES_USERNAME
            - POSTGRES_PASSWORD
            - POSTGRES_DATABASE

volumes:
    sample_db:

networks:
    app-net:
        driver: bridge
