version: '3'

services:

    app:
        depends_on:
            - rabbitmq
            - celery
        environment:
            - RABBITMQ_HOST
            - RABBITMQ_PORT

    rabbitmq:
        hostname: my-rabbit
        container_name: rabbit
        image: rabbitmq:3-alpine
        networks:
            - app-net
        ports:
            - '5672:5672'
            - '15672:15672'
        volumes:
            - "../rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf"
      
    celery:
        build:
            context: ./worker
            dockerfile: celery.Dockerfile
        container_name: worker
        networks:
            - app-net
        depends_on:
            - rabbitmq
        environment:
            - RABBITMQ_HOST=rabbitmq
            - RABBITMQ_PORT=5672
            - RABBITMQ_USERNAME=guest
            - RABBITMQ_PASSWORD=guest

networks:
    app-net:
        driver: bridge
