name: postgres_api
channels:
  - defaults
  - conda-forge
dependencies:
  - anyio=3.5.0
  - argon2-cffi=21.3.0
  - argon2-cffi-bindings=21.2.0
  - asttokens=2.0.5
  - atomicwrites=1.4.0
  - attrs=21.4.0
  - babel=2.9.1
  - backcall=0.2.0
  - beautifulsoup4=4.11.1
  - bleach=4.1.0
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - ca-certificates=2022.10.11
  - certifi=2022.9.24
  - cffi=1.15.1
  - charset-normalizer=2.0.4
  - click=8.0.4
  - colorama=0.4.5
  - cryptography=38.0.1
  - debugpy=1.5.1
  - decorator=5.1.1
  - defusedxml=0.7.1
  - entrypoints=0.4
  - executing=0.8.3
  - faker=8.8.1
  - fastapi=0.87.0
  - greenlet=1.1.1
  - h11=0.12.0
  - h2=4.0.0
  - hpack=4.0.0
  - httpcore=0.15.0
  - httpx=0.23.0
  - hyperframe=6.0.1
  - idna=3.4
  - iniconfig=1.1.1
  - ipykernel=6.15.2
  - ipython=8.6.0
  - ipython_genutils=0.2.0
  - jedi=0.18.1
  - jinja2=3.1.2
  - json5=0.9.6
  - jsonschema=4.16.0
  - jupyter_client=7.3.5
  - jupyter_core=4.11.2
  - jupyter_server=1.18.1
  - jupyterlab=3.4.4
  - jupyterlab_pygments=0.1.2
  - jupyterlab_server=2.15.2
  - krb5=1.19.2
  - libffi=3.4.2
  - libiconv=1.16
  - libpq=12.9
  - libsodium=1.0.18
  - libxml2=2.9.14
  - libxslt=1.1.35
  - lxml=4.9.1
  - markupsafe=2.1.1
  - matplotlib-inline=0.1.6
  - mistune=0.8.4
  - nbclassic=0.4.8
  - nbclient=0.5.13
  - nbconvert=6.5.4
  - nbformat=5.5.0
  - nest-asyncio=1.5.5
  - notebook=6.5.2
  - notebook-shim=0.2.2
  - openssl=1.1.1s
  - packaging=21.3
  - pandocfilters=1.5.0
  - parso=0.8.3
  - pickleshare=0.7.5
  - pip=22.2.2
  - pluggy=1.0.0
  - postgresql=12.9
  - prometheus_client=0.14.1
  - prompt-toolkit=3.0.20
  - psutil=5.9.0
  - psycopg2=2.9.3
  - pure_eval=0.2.2
  - py=1.11.0
  - pycparser=2.21
  - pydantic=1.10.2
  - pygments=2.11.2
  - pyopenssl=22.0.0
  - pyparsing=3.0.9
  - pyrsistent=0.18.0
  - pysocks=1.7.1
  - pytest=7.1.2
  - python=3.10.8
  - python-dateutil=2.8.2
  - python-dotenv=0.21.0
  - python-fastjsonschema=2.16.2
  - python_abi=3.10
  - pytz=2022.1
  - pywin32=302
  - pywinpty=2.0.2
  - pyzmq=23.2.0
  - requests=2.28.1
  - rfc3986=1.4.0
  - send2trash=1.8.0
  - setuptools=65.5.0
  - six=1.16.0
  - sniffio=1.2.0
  - soupsieve=2.3.2.post1
  - sqlalchemy=1.4.39
  - sqlite=3.39.3
  - stack_data=0.2.0
  - starlette=0.21.0
  - terminado=0.13.1
  - text-unidecode=1.3
  - tinycss2=1.2.1
  - tk=8.6.12
  - tomli=2.0.1
  - tornado=6.2
  - traitlets=5.1.1
  - typing-extensions=4.3.0
  - typing_extensions=4.3.0
  - tzdata=2022f
  - urllib3=1.26.12
  - uvicorn=0.19.0
  - vc=14.2
  - vs2015_runtime=14.27.29016
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - websocket-client=0.58.0
  - wheel=0.37.1
  - win_inet_pton=1.1.0
  - wincertstore=0.2
  - winpty=0.4.3
  - xz=5.2.6
  - zeromq=4.3.4
  - zlib=1.2.13
