name: postgres_api
channels:
  - defaults
  - conda-forge
dependencies:
  - numpy
  - sqlalchemy
  - faker
  - python-dotenv
  - pandas
  - uvicorn
  - postgresql
  - psycopg2
  - fastapi
  - jupyterlab
  - python
  - pytest
  - httpx
